name: smart_fridge
description: "Make your fridge smarter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^4.0.4
  http: ^0.13.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/smart_fridge.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/smart_fridge.png
  android: true
  ios: true